/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Waypoint', function() {
      beforeEach(function() {
        instance = new StravaApiV3.Waypoint();
      });

      it('should create an instance of Waypoint', function() {
        // TODO: update the code to test Waypoint
        expect(instance).to.be.a(StravaApiV3.Waypoint);
      });

      it('should have the property latlng (base name: "latlng")', function() {
        // TODO: update the code to test the property latlng
        expect(instance).to.have.property('latlng');
        // expect(instance.latlng).to.be(expectedValueLiteral);
      });

      it('should have the property targetLatlng (base name: "target_latlng")', function() {
        // TODO: update the code to test the property targetLatlng
        expect(instance).to.have.property('targetLatlng');
        // expect(instance.targetLatlng).to.be(expectedValueLiteral);
      });

      it('should have the property categories (base name: "categories")', function() {
        // TODO: update the code to test the property categories
        expect(instance).to.have.property('categories');
        // expect(instance.categories).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property distanceIntoRoute (base name: "distance_into_route")', function() {
        // TODO: update the code to test the property distanceIntoRoute
        expect(instance).to.have.property('distanceIntoRoute');
        // expect(instance.distanceIntoRoute).to.be(expectedValueLiteral);
      });

    });
  });

}));
